### ISSUE TITLE
Failed to compile after decompile ('versionName' with value '?????')

### ISSUE THREAD

**Issue by RadarNyan** [Furniel/Apk-Changer#14]
Just cloned master, installed with default settings, tried to decomplie/compile base.apk (https://play.google.com/store/apps/details?id=com.fc2.blog9.zze128.kiguchiprjx&hl=ja)

Log
```
I: Compiling base...
W: C:\Users\misaki\PublicZone\Apk-Changer-master\out\base\AndroidManifest.xml:2: error: Error: No resource found that matches the given name (at 'versionName' with value '?????').
W: 
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [aapt, p, --forced-package-id, 127, --min-sdk-version, 14, --target-sdk-version, 24, --version-code, 12, --version-name, ?????, --no-version-vectors, -F, C:\Users\misaki\AppData\Local\Temp\APKTOOL5655174236270215970.tmp, -0, arsc, -I, C:\Users\misaki\AppData\Local\apktool\framework\1-api24.apk, -S, C:\Users\misaki\PublicZone\Apk-Changer-master\out\base\res, -M, C:\Users\misaki\PublicZone\Apk-Changer-master\out\base\AndroidManifest.xml]
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:477)
	at brut.androlib.Androlib.buildResources(Androlib.java:411)
	at brut.androlib.Androlib.build(Androlib.java:310)
	at brut.androlib.Androlib.build(Androlib.java:263)
	at brut.apktool.Main.cmdBuild(Main.java:227)
	at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [aapt, p, --forced-package-id, 127, --min-sdk-version, 14, --target-sdk-version, 24, --version-code, 12, --version-name, ?????, --no-version-vectors, -F, C:\Users\misaki\AppData\Local\Temp\APKTOOL5655174236270215970.tmp, -0, arsc, -I, C:\Users\misaki\AppData\Local\apktool\framework\1-api24.apk, -S, C:\Users\misaki\PublicZone\Apk-Changer-master\out\base\res, -M, C:\Users\misaki\PublicZone\Apk-Changer-master\out\base\AndroidManifest.xml]
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:440)
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:463)
	... 5 more
Caused by: brut.common.BrutException: could not exec (exit code = 1): [aapt, p, --forced-package-id, 127, --min-sdk-version, 14, --target-sdk-version, 24, --version-code, 12, --version-name, ?????, --no-version-vectors, -F, C:\Users\misaki\AppData\Local\Temp\APKTOOL5655174236270215970.tmp, -0, arsc, -I, C:\Users\misaki\AppData\Local\apktool\framework\1-api24.apk, -S, C:\Users\misaki\PublicZone\Apk-Changer-master\out\base\res, -M, C:\Users\misaki\PublicZone\Apk-Changer-master\out\base\AndroidManifest.xml]
	at brut.util.OS.exec(OS.java:95)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:434)
	... 6 more
```

decompiled AndroidManifest.xml
```xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="com.fc2.blog9.zze128.kiguchiprjx" platformBuildVersionCode="24" platformBuildVersionName="7.0">
    <uses-permission android:name="com.android.launcher.permission.INSTALL_SHORTCUT"/>
    <application android:allowBackup="true" android:icon="@mipmap/ic_launcher" android:label="@string/app_name" android:supportsRtl="true" android:theme="@style/AppTheme">
        <activity android:name="com.fc2.blog9.zze128.kiguchiprjx.MainActivity">
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
        <activity android:name="com.fc2.blog9.zze128.kiguchiprjx.AppListActivity"/>
        <activity android:name="com.fc2.blog9.zze128.kiguchiprjx.DisplayActivity"/>
        <activity android:name="com.fc2.blog9.zze128.kiguchiprjx.PrefarencesActivity"/>
        <meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version"/>
    </application>
</manifest>
```

**Comment by RadarNyan** [comment]
It will work if I manually add a "android:versionName"  into <manifest>
I believe the problem is that apk-changer can't handle non-numbered versionName. (for this app, the versionName is written in Japanens Kanji)
