### ISSUE TITLE
Java runs out of memory while decompiling framework jar to java source

### ISSUE THREAD

**Issue by matejdro** [Furniel/Apk-Changer#5]
```
------------------------------------------------------------------------- 
-----------------------|ned 31.05.2015 -- 13:46:43,50|----------------------- 
------------------------------------------------------------------------- 
java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)
Exception in thread "pool-1-thread-5" java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.util.Arrays.copyOfRange(Arrays.java:3664)
	at java.lang.String.<init>(String.java:201)
	at java.lang.StringBuilder.toString(StringBuilder.java:407)
	at jadx.core.codegen.CodeWriter.toString(CodeWriter.java:269)
	at java.lang.String.valueOf(String.java:2982)
	at java.lang.StringBuilder.append(StringBuilder.java:131)
	at jadx.core.codegen.CodeWriter.add(CodeWriter.java:116)
	at jadx.core.codegen.ClassGen.makeClass(ClassGen.java:104)
	at jadx.core.codegen.CodeGen.visit(CodeGen.java:19)
	at jadx.core.ProcessClass.process(ProcessClass.java:43)
	at jadx.api.JadxDecompiler.processClass(JadxDecompiler.java:281)
	at jadx.api.JavaClass.decompile(JavaClass.java:59)
	at jadx.api.JadxDecompiler$1.run(JadxDecompiler.java:161)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Exception in thread "pool-1-thread-7" java.lang.OutOfMemoryError: GC overhead limit exceeded
Exception in thread "pool-1-thread-1" java.lang.OutOfMemoryError: GC overhead limit exceeded
SLF4J: Failed toString() invocation on an object of type [jadx.core.dex.nodes.BlockNode]
java.lang.OutOfMemoryError: GC overhead limit exceeded
SLF4J: Failed toString() invocation on an object of type [java.util.ArrayList]
java.lang.OutOfMemoryError: GC overhead limit exceeded
Exception in thread "pool-1-thread-10" java.lang.OutOfMemoryError: GC overhead limit exceeded
Exception in thread "pool-1-thread-2" java.lang.OutOfMemoryError: GC overhead limit exceeded
Exception in thread "pool-1-thread-4" java.lang.OutOfMemoryError: GC overhead limit exceeded
Exception in thread "pool-1-thread-11" java.lang.OutOfMemoryError: GC overhead limit exceeded
Exception in thread "pool-1-thread-13" java.lang.OutOfMemoryError: GC overhead limit exceeded
```

Through whole time I still had gigabytes of free RAM so I assume not enough of it is allocated to java? Just smali decompiling works fine though.

**Comment by Furniel** [comment]
Go to settings -> cache size and set it to 1024. I`m thinking about adding bigger memory limits to settings, according to tests(http://stackoverflow.com/questions/1434779/maximum-java-heap-size-of-a-32-bit-jvm-on-a-64-bit-os) for x86 java maximum safe size can be set to 1.5GB, and if you use x64 jvm maximum memory size is 3TB. Today i`ll try to change setiings and make maximum limit for x86 jvm to 1.5gb and for x64 jvm 4gb or 8gb limit should be enough.
